[lua]
style = "bold white"
symbol = "  "
disabled = false
format = "[$symbol($version )]($style)"

[python]
style = "bold white"
symbol = "  "
disabled = false
format = "[$symbol($version )]($style)"

[cpp]
style = "bold white"
symbol = "  "
disabled = false
format = "[$symbol($version )]($style)"
